### ISSUE TITLE
Error creating compatibility symlinks with latest Processing Pi Image

### ISSUE THREAD

**Issue by EPstudios** [gohai/processing-uploadtopi#13]
I seem to be getting an error when trying to upload your gl video examples.
Using the latest processing pi image and tried 3.3.7 and 3.4 from my macbook.

Other sketches seem to load ok. Any advice?

`GLVideo: Error creating compatibility symlinks
java.lang.UnsatisfiedLinkError: /home/pi/VideoMapping/lib/libglvideo.so: libGLESv2.so: cannot open shared object file: No such file or directory
	at processing.opengl.PSurfaceJOGL$2.run(PSurfaceJOGL.java:408)
	at java.lang.Thread.run(Thread.java:745)
`

**Comment by gohai** [comment]
Does the sketch still run? (I'll look into it)

**Comment by EPstudios** [comment]
Sorry for the delay in reply. No it doesnt, hangs on a black frame (SingleVideo) or a white frame (VideoMappingWithShader).

The pi in question is a 3b v1.2, will be able to try with some 3b+ next week and try uploading from some other hardware. Anything else that could be of help please let me know.

Edit: Probably also worth mentioning that the sketches run fine when directly run through processing on the Pi, the sketches behave the same (hanging, cant even escape to exit) when trying to run them as an exported aplication.
