### ISSUE TITLE
P3D issue while uploading

### ISSUE THREAD

**Issue by ffd8** [gohai/processing-uploadtopi#9]
Using Processing 3.3.5, UploadToPi 1.0.6, RaspberryPi 3 (using latest Raspbian) – I can run a Processing sketch with P3D fine within the RPi and Processing.. however if I try to send the app via UploadToPi, I get the following error:

`libEGL warning: DRI2: failed to authenticate
java.lang.RuntimeException: java.lang.ClassNotFoundException: Failed to find NEWT Display Class <.bcm.vc.iv.DisplayDriver>
	at jogamp.newt.DisplayImpl.create(DisplayImpl.java:314)
	at com.jogamp.newt.NewtFactory.createDisplay(NewtFactory.java:167)
	at com.jogamp.newt.NewtFactory.createDisplay(NewtFactory.java:149)
	at processing.opengl.PSurfaceJOGL.initDisplay(PSurfaceJOGL.java:149)
	at processing.opengl.PSurfaceJOGL.initFrame(PSurfaceJOGL.java:135)
	at processing.core.PApplet.initSurface(PApplet.java:10877)
	at processing.core.PApplet.runSketch(PApplet.java:10764)
	at processing.core.PApplet.main(PApplet.java:10464)
	at alpha_template.main(alpha_template.java:137)
Caused by: java.lang.ClassNotFoundException: Failed to find NEWT Display Class <.bcm.vc.iv.DisplayDriver>
	at jogamp.newt.DisplayImpl.getDisplayClass(DisplayImpl.java:277)
	at jogamp.newt.DisplayImpl.create(DisplayImpl.java:285)
	... 8 more`

Any ideas??

**Comment by gohai** [comment]
@ffd8 Please try with Processing 3.3.6. I re-released 3.3.5 for ARM with some fixes for the latest Raspbian baked in, but when you're building on another machine you will need 3.3.6 for these bits. (Feel free to reopen if this doesn't solve it.)
